### PR TITLE
Implement Emoji Seeding Features 

### LINKED ISSUE #21: "React if coming or not" emoji seeding

### PR DESCRIPTION
**Pull request by shirleyfyx**
## Description

This pull request introduces several enhancements to the Slack bot's emoji functionalities. It includes the implementation of new TypeScript functions for generating emoji pairs, seeding message reactions, and integrating with Slack's emoji APIs.

This PR closes #21.

## Changes

1. generateEmojiPair Function:

- Implemented an asynchronous function to generate a pair of distinct emojis.
Ensures that the selected emojis are different, with a fallback to default emojis if needed.

2. seedMessageReactions Function:

- Added functionality to seed reactions to a message on a Slack channel.
Ensures reactions are added sequentially with a delay between them.

3. Integration with Slack Web API:

- Utilized the @slack/web-api package to add and list emojis.

## Developer Testing: 

- Manually tested in Slack development. Random emojis were added to the message successfully.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56)

### CODE REVIEW

**Comment by shirleyfyx** [comment]
Tested in Slack development. Random emojis were added to the message. 
image

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Just a few fixes to the structure of your files. Also, please sync this branch with `main`. 

I haven't taken a good look at the code itself, but will do so once you make the changes above and re-request me for a review.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-:-NmHgSSF2v7TPiWlBWnS:b-4w1jub)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/events/slack-emojis.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmHfGrV2U-bArjnWYtP:-NmHfGrW5lILauN1czI-:b29rsng) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/6964ef436e9c4a11b791413d0818ae7f5d890099/src/listeners/events/slack-emojis.ts#L0)):*
File naming convention for TS is usually camelCase. Rename to `slackEmojis.ts`?
Also, I think it would make sense for this file to belong in `/src/utils/`.  The `listeners/events` folder is meant for event listeners (e.g. `app.event('app_home_opened', appHomeOpenedCallback)`) which this is not
___
*[`src/utils/handlers/slack-handler.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmHfSLf1KRh3QQnd2j4:-NmHfSLf1KRh3QQnd2j5:byy7gb3) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/6964ef436e9c4a11b791413d0818ae7f5d890099/src/utils/handlers/slack-handler.ts#L0)):*
File naming convention for TS is usually camelCase. Rename to `slackHandler.ts`?
Additionally, it would be good to do away with the `slack-handler` file that we had in old minerva, which contained all of the functionality for interacting with Slack. It might be better for all of this to be in `slackEmoji.ts`

**Review by Darth-Raazi — COMMENTED** [review]
Code looks good to me, but the emoji feature wasn't working in dev slack. I probably did something wrong but I'll let Chamath give the official approval for this one

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-:-NmLlZsy0QkNAPNad4d7:b-dilpoi)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Review by QuantumManiac — COMMENTED** [review]
> Code looks good to me, but the emoji feature wasn't working in dev slack

There is currently nothing exposing the functionality, allowing testers to actually test it in the Dev Slack. @shirleyfyx this is probably a good thing for us to keep in mind for the future: keep the testing code that we use to verify functionality so that reviewers can use it to test the function themselves, and only remove it once we have the PR approvals we need, right before merging.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-:-NmMLNiC6Ysz_jfk_rVD:b-lxflgq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Looks good so far! I left a few comments. There's a bit more left to review, but I would rather review that once you commented your code and wrote up some JSDocs for it so I have a better idea of what's going on.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-:-NmMR-wS881xMYpeh6vs:bosh12a)* status: all files reviewed, 7 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/events/slackEmojis.ts` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMMQhm0B0N-A6lHaDv:-NmMMQhm0B0N-A6lHaDw:b2dlp98) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L0)):*
Could we move this out of `src/listeners` to somewhere else, as mentioned before? I think `src/utils` might be fine for now.
___
*[`src/listeners/events/slackEmojis.ts` line 4 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMMcE_6Bozr7lr7FLx:-NmMMcE_6Bozr7lr7FLy:bteeldh) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L4)):*
> ```XML
> 
> // https://api.slack.com/methods/reactions.add
> export function addReactionToMessage(
> ```

Can you add some JSDocs to all these functions? [This SO thread is a good place to find out how](https://stackoverflow.com/questions/34220564/is-there-a-way-to-generate-jsdoc-comments-in-visual-studio-code), and you can use the functions that I've written JSDocs for as a reference if you want an idea of how to write them up.
___
*[`src/listeners/events/slackEmojis.ts` line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMNh5s17JR_bfHfAOQ:-NmMNh5s17JR_bfHfAOR:bsij05z) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L9)):*
> ```XML
>   emoji: string,
>   timestamp: string | number,
> ): Promise<unknown> {
> ```

The return type should be more specific than `Promise<unknown>`. Looking at the return type for `app.client.reactions.add`, this should be `Promise<ReactionsAddResponse>` if possible.
___
*[`src/listeners/events/slackEmojis.ts` line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMNUld6J_Ept3SqNzi:-NmMNUld6J_Ept3SqNzj:b3f1hkc) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L12)):*
> ```XML
>   // Convert timestamp to string if it's a number
>   const timestampStr =
>     typeof timestamp === 'number' ? timestamp.toString() : timestamp;
> ```

Please change all single-quotes to double-quotes. Either the ESLint or Prettier extension should be taking care of this for you, do you have them set up?
___
*[`src/listeners/events/slackEmojis.ts` line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMPzXMEUc1ciXXDjAC:-NmMPzXMEUc1ciXXDjAD:b-j9ckky) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L24)):*
> ```XML
> export async function getRandomEmoji(app: App): Promise<string> {
>   try {
>     const result = await app.client.emoji.list();
> ```

It's usually good practice to wrap API calls like this into a function of its own, even if it is super-simple like this, as it makes unit testing easier. Can you move this out into a `getAllEmojis` function?
___
*[`src/listeners/events/slackEmojis.ts` line 49 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMPTnaDDrPWNZTyiCo:-NmMPTnaDDrPWNZTyiCp:bguohor) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L49)):*
> ```XML
> }
> 
> export async function generateEmojiPair(app: App): Promise<string[]> {
> ```

This, along with `getRandomEmoji` looks to be straight from the original Minerva. You might be able to rewrite it in a bit more elegant and clean way. You don't have to if you don't want to, but give it a shot if you'd like

I think a good way to go about this would be to get the entire list of emojis and randomly pick two different emojis at the same time instead of independently picking two random emojis, one at a time, and then having to check if two of the same were picked or something.
___
*[`src/listeners/events/slackEmojis.ts` line 79 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMQpRP0j8SyyocGjD9:-NmMQpRP0j8SyyocGjDA:bcwlpy1) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L79)):*
> ```XML
>     setTimeout(async () => {
>       await addReactionToMessage(app, channel, emojis[1], timestamp);
>     }, 1000);
> ```

Now that we're working with a dedicated server, we might be able to reduce this delay, or remove it entirely. Can you do some experimenting and see what you can get away with?

**Comment by shirleyfyx** [comment]
Thanks! I will update the changes.

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56)* status: all files reviewed, 4 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/messages/index.ts` line 11 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmkfCFzDdopCOJTqz_1:-NmkfCFzDdopCOJTqz_2:b-pfaa9r) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/b0b2e6c46caa1ff4a1c5e719fd0978d2d2840058/src/listeners/messages/index.ts#L11)):*
> ```XML
> const register = (app: App) => {
>   app.message(/^(hi|hello|hey).*/, helloMessageCallback);
> ```

Code looks good, and come to think of it, it might be a good idea to have this functionality for testing even for after this PR is merged. We can just remove it before we run minerva in production.

That being said, can you move all this functionality into its own file under `listeners/messages`, like what you see with `helloMessageCallback`?
___
*[`src/listeners/events/slackEmojis.ts` line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NmMPzXMEUc1ciXXDjAC:-NnEsCWICZ3W1dU7GeZp:bsb1lav) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3cb2d1b75ddfaa2b365a0da1bd90e4ce01b035a3/src/listeners/events/slackEmojis.ts#L24)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It's usually good practice to wrap API calls like this into a function of its own, even if it is super-simple like this, as it makes unit testing easier. Can you move this out into a `getAllEmojis` function?
</blockquote></details>

Can you also move this into `utils/slack.ts`, as it interacts with the Slack API directly?
___
*[`src/utils/slackEmojis.ts` line 94 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NnEtT5y-_jlVpnrFIt8:-NnEtT5y-_jlVpnrFIt9:b-u8kgst) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/a3e799c5bd778264797fdeb474a8a68f95492a2e/src/utils/slackEmojis.ts#L94)):*
> ```XML
>   const response = await addReactionToMessage(app, channel, emojis[0], timestamp);
> 
>   if (isSlackAPIResponse(response) && response.ok) {
> ```

I don't think you need `isSlackAPIResponse` for this. `addReactionToMessage` always returns a promise for a `ReactionsAddResponse` so you'll always be able to check for `response.ok` since it will never not be a Slack API response

**Review by QuantumManiac — APPROVED** [review]
LGTM, just some nits relating to updating the JSDocs for some functions.

Make sure to fix the merge conflicts before merging.

> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-:-NnjkcReDNw-59rN6nvm:b-rzvwca)* status: all files reviewed, 3 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/utils/slackEmojis.ts` line 8 at r6](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NnjjGhbCAOoT7ektdG6:-NnjjGhbCAOoT7ektdG7:undefined) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/96157ff595479d6d4bba01cb7f0a4d8a134f0a32/src/utils/slackEmojis.ts#L8)):*
> ```XML
> /**
>  * Adds a reaction to a specific message in a Slack channel.
>  * @param client The Slack App instance.
> ```





_Suggestion:_
```XML
 * @param client The Slack Web API client
```
___
*[`src/utils/slackEmojis.ts` line 33 at r6](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56#-NnjjS3Z-Gj9ZpgAe7-p:-NnjjS3Z-Gj9ZpgAe7-q:undefined) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/96157ff595479d6d4bba01cb7f0a4d8a134f0a32/src/utils/slackEmojis.ts#L33)):*
> ```XML
>  * Generates a pair of unique, random emoji from the available set in a Slack workspace.
>  * If there are not enough emojis, defaults to ["white_check_mark", "x"].
>  * @param client The Slack App instance.
> ```





_Suggestion:_
```XML
 * @param client The Slack Web API client
```

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/56)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Pull request merged**
