### PR TITLE
Implement Periodic Event Checking

### LINKED ISSUE #18: Periodic Checking for Meetings
Dependencies:
- #17

### PR DESCRIPTION
**Pull request by QuantumManiac**
## Description

Implemented functionality to allow for periodic checking for upcoming calendar events, which can then be used to generate event reminder messages in Slack.

The current implementation checks for events that are 5 minutes and 6 hours away, as those are the times that old minerva uses to send its two event reminders per message. The function will detect that an event is to be reminded for as long as it's within +/- 2.5 minutes of the target time until meeting. 

I have also built up the foundations for actually posting the meeting reminders, as it was necessary to write up functionality for reviewer testing.

Apologies, the diff on this is a slight mess as I added a linting command (`yarn lint`) midway through development and there were a lot of unlinted files that it linted. 

This PR closes #18.

## Developer Testing

Testing done:
- Manually tested by deploying the app to dev, moving events around on the dev Google Calendar, and ensuring that behavior is as expected
- Implemented unit tests for `isTimeWithinBounds` and `getEventReminderType`

## Reviewer Testing

Testing this functionality is a bit tricky as the reminder check only executes every five minutes.
1. Create a Google Calendar event on the Dev Google Calendar, making sure to add all the necessary metadata (minimally, a channel name - ensure that channel actually exists in the dev slack)
2. Move the event to a suitable start time to test the functionality with (e.g. moving the event to +5 mins or +6 hours from the next five-minute mark is good to test those meeting reminders)
3. Wait for the five-minute mark so the function executes
4. Ensure that a message was posted to a channel in the format of `I should be generating a reminder for Software at Fri Dec 29 2023 17:10:00 GMT-0500 (Eastern Standard Time) with reminder type SIX_HOURS!`

If the message was not posted, ensure that minerva is actually in the channel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59)

### CODE REVIEW

**Review by QuantumManiac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`ecosystem.config.js` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZ5h15b26BBnBZc91:-NmqZ5h15b26BBnBZc92:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/ecosystem.config.js#L0)):*
Just linting, please ignore.
___
*[`package.json` line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZ8SUDUCJ1lYjbU7p:-NmqZ8SUDUCJ1lYjbU7q:b41uy9q) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/package.json#L9)):*
> ```JSON
>     "deploy-dev": "git push -f origin +@:development && echo 'View deployment at https://github.com/waterloo-rocketry/minerva-rewrite/deployments?environment=development#activity-log'",
>     "test": "jest",
>     "lint": "eslint . --fix --ext .js,.ts --ignore-pattern node_modules"
> ```

Added a lint command here
___
*[`tsconfig.json` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZAWVBJJQfdJGiyIr:-NmqZAWVBJJQfdJGiyIs:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/tsconfig.json#L0)):*
Just linting, please ignore.
___
*[`webpack.config.cjs` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZBg34OlaJDOsC2BL:-NmqZBg34OlaJDOsC2BM:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/webpack.config.cjs#L0)):*
Just linting, please ignore.
___
*[`.github/workflows/deploy_development.yml` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZEEd7jJY-GiEAav9:-NmqZEEd7jJY-GiEAavA:b4fykpi) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/.github/workflows/deploy_development.yml#L0)):*
I saw that we weren't actually adding a `NODE_ENV` env variable when deploying, so I snuck it in
___
*[`src/classes/CalendarEvent.ts` line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZN3_8Qj3nUVnE2dz:-NmqZN3_8Qj3nUVnE2e-:b-wmibtp) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/classes/CalendarEvent.ts#L40)):*
> ```XML
>    * @returns The parsed CalendarEvent object
>    */
>   static fromGoogleCalendarEvent(event: calendar_v3.Schema$Event, workspaceChannels: SlackChannel[]): CalendarEvent {
> ```

Refactored parsing GCal events into a static method so you can create fake events more easily.
___
*[`src/listeners/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZUW-By87O1zIBS6I:-NmqZUW-By87O1zIBS6J:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/index.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/actions/buttonClick.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZVVEEiuBsbJL24-D:-NmqZVVEEiuBsbJL24-E:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/actions/buttonClick.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/actions/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZWJ71tFwtw5wP8qW:-NmqZWJ71tFwtw5wP8qX:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/actions/index.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/commands/helpCommand.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZXA5BfDh6k0tmWVu:-NmqZXA5BfDh6k0tmWVv:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/commands/helpCommand.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/commands/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZYKcEb89xe67HKq2:-NmqZYKcEb89xe67HKq3:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/commands/index.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/events/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZYyqCik38piSVaPB:-NmqZYyqCik38piSVaPC:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/events/index.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/messages/helloMessage.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZa75EbxF7e0HwhOP:-NmqZa75EbxF7e0HwhOQ:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/messages/helloMessage.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/messages/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZatWBpcA2wCJzhtj:-NmqZatWBpcA2wCJzhtk:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/messages/index.ts#L0)):*
Just linting, please ignore.
___
*[`src/listeners/views/index.ts` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZb_e4p7d-mAxZozf:-NmqZb_e4p7d-mAxZozg:b2ljux6) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/listeners/views/index.ts#L0)):*
Just linting, please ignore.

**Review by wxp02 — APPROVED** [review]
Great work here! Also nice job refactoring the events parser into a static method to create fake events more easily
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-:-Nmsfbsj9bMUwfRWixzz:b-fzksip)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, and @yxyyeah)

___
*[`src/classes/CalendarEvent.ts` line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZN3_8Qj3nUVnE2dz:-Nmsetun72FudQ-5XeUm:bb70w76) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/src/classes/CalendarEvent.ts#L40)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Refactored parsing GCal events into a static method so you can create fake events more easily.
</blockquote></details>

Nice

**Review by shirleyfyx — APPROVED** [review]
:lgtm: Nice work! Great to format all the files too! 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-:-NnAY76WClzIE8TR0uTz:bxgz4yp)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @slightlyskepticalpotat, and @yxyyeah)

___
*[`.github/workflows/deploy_development.yml` line  at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-NmqZEEd7jJY-GiEAav9:-NnAYTNaCEXqgUwJfrbA:btojbfd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/9bdd36add24b10e71d3c3b96ab0cceeba60a0f0d/.github/workflows/deploy_development.yml#L)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

I saw that we weren't actually adding a `NODE_ENV` env variable when deploying, so I snuck it in
</blockquote></details>

Great!

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 24 of 26 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/59#-:-NnAtUmj67JB_VCHdtw3:bnfp4nl)* status: all files reviewed, 15 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @slightlyskepticalpotat, and @yxyyeah)

**Pull request merged**
