### PR TITLE
set up node.js and typescript

### PR DESCRIPTION
**Pull request by billyao021031**
Have Yarn, Node.js and Typescript set up for the repository 
Screen Shot 2023-10-07 at 8 31 23 PM

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031)

___
*[`.editorconfig` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-NgBkrFiBu_tS6TpQeuM:-NgBkrFiBu_tS6TpQeuN:b-cxe6cd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/207e059bc23e1b75da9abce1775a69ce43f635ba/.editorconfig#L0)):*
Was this created from `yarn init`?
___
*[`package.json` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-NgBl4OS4rSA7he0nD5u:-NgBl4OS4rSA7he0nD5v:b1yzm18) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/207e059bc23e1b75da9abce1775a69ce43f635ba/package.json#L2)):*
> ```JSON
> {
>   "name": "minerva-rewrite",
> ```

This might be jumping the gun a bit but it might be good to set up a build script so we can transpile our TypeScript using `yarn build`



_Suggestion:_
```JSON
  "name": "minerva-rewrite",
  "scripts": {
    "build": "tsc -p ."
  },
  "packageManager": "yarn@3.6.4",
```

**Comment by billyao021031** [comment]
> > Reviewed 7 of 7 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27)_ status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031)
> 
> _[`.editorconfig` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-NgBkrFiBu_tS6TpQeuM:-NgBkrFiBu_tS6TpQeuN:b-cxe6cd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/207e059bc23e1b75da9abce1775a69ce43f635ba/.editorconfig#L0)):_ Was this created from `yarn init`?
> 
>> I think we could remove it as it does not affect anything else other than IDE formatting. 
> _[`package.json` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-NgBl4OS4rSA7he0nD5u:-NgBl4OS4rSA7he0nD5v:b1yzm18) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/207e059bc23e1b75da9abce1775a69ce43f635ba/package.json#L2)):_
> 
> > ```json
> > {
> >   "name": "minerva-rewrite",
> > ```
> 
> This might be jumping the gun a bit but it might be good to set up a build script so we can transpile our TypeScript using `yarn build`
> 
> _Suggestion:_
> 
> ```json
>   "name": "minerva-rewrite",
>   "scripts": {
>     "build": "tsc -p ."
>   },
>   "packageManager": "yarn@3.6.4",
> ```

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-:-NgFpZyl9GSiuasljG7S:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031)

___
*[`.editorconfig` line  at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27#-NgBkrFiBu_tS6TpQeuM:-NgFpR6C3rS14x3hZQj8:brx2xig) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/207e059bc23e1b75da9abce1775a69ce43f635ba/.editorconfig#L)):*
<details><summary><i>Previously, billyao021031 (Bohan Yao) wrote…</i></summary><blockquote>

I think we could remove it as it does not affect anything else other than IDE formatting. 
</blockquote></details>

Yep, it shouldn't actually do anything unless your IDE is set up to do so.

**Review by QuantumManiac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @billyao021031)

**Pull request merged**
