### PR TITLE
Create Initial Slack Application

### LINKED ISSUE #14: Create initial Slack application
As discussed in the kick-off, this will most likely be set up using [Bolt](https://github.com/slackapi/bolt-js)

### PR DESCRIPTION
**Pull request by billyao021031**
## Description
Set up the initial slack appliation and directory structure for the project. There's currently not much, except for boilerplate code and some examples that can be used for reference in further developing the app.

The slackbot currently only has one piece of functionality: messaging "hi", "hello", or "hey" into a channel that the slackbot is in will result in it responding to you with a message. This message contains a button that if clicked will acknowledge the button press with another message.

This PR closes #14.

## Developer Testing

Testing done:
- Deployed the application to development and tested the hey/hi/hello message reponse and button click

## Reviewer Testing

Note that testing requires joining the Waterloo Rocketry DEV Slack. Instructions are pinned in `#software`. 

1. In the Dev slack, message "hey", "hi", or "hello" in any channel that minerva is in. If minerva is not in a channel, you can add them by pinging them (`sending @minervadev in a message`)
2. Check that minerva responds to your message. 
3. Click the button that is on the response message and see if it results in another response message.
 

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Please use the PR template for the PR description. Also, have you tested to see if this functionality works?

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Code mostly looks good other than a few questions I have, but blocking until testing information has been added (see Chamath's comment)

> Reviewed 3 of 4 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-:-NjrqJrIABrO_P-ojV6i:bupx7cc)* status: all files reviewed, 4 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/commands/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-Njrq3ju3PRXyjbGK9n6:-Njrq3ju3PRXyjbGK9n7:b-89ew3v) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/commands/index.ts#L5)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> const register = (app: App) => {
>   //   app.command('/sample-command', sampleCommandCallback);
> ```

Is this supposed to be commented out?
___
*[`src/listeners/events/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-Njrq74b5zqL5y2U_7Pr:-Njrq74b5zqL5y2U_7Ps:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/events/index.ts#L5)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> const register = (app: App) => {
>   //   app.event('app_home_opened', appHomeOpenedCallback);
> ```

See above
___
*[`src/listeners/shortcuts/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-NjrqERw9X-TXZUgy9ee:-NjrqERw9X-TXZUgy9ef:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/shortcuts/index.ts#L5)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> const register = (app: App) => {
>   //   app.shortcut('sample_shortcut_id', sampleShortcutCallback);
> ```

See above
___
*[`src/listeners/views/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-NjrqGZjD-j6b-l9BH-d:-NjrqGZjD-j6b-l9BH-e:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/views/index.ts#L5)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> const register = (app: App) => {
>   //   app.view('sample_view_id', sampleViewCallback);
> ```

See above

**Review by QuantumManiac — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52)* status: all files reviewed, 4 unresolved discussions (waiting on @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/commands/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-Njrq3ju3PRXyjbGK9n6:-NjsQo6t0pv-C_23PDxU:b-6n2buo) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/commands/index.ts#L5)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Is this supposed to be commented out?
</blockquote></details>

Yes, just an example to show how functionality should be added here.
___
*[`src/listeners/events/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-Njrq74b5zqL5y2U_7Pr:-NjsQtIf5TYQn4D5CRFr:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/events/index.ts#L5)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above
___
*[`src/listeners/shortcuts/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-NjrqERw9X-TXZUgy9ee:-NjsQuJEAtt89eAOuBWD:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/shortcuts/index.ts#L5)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above
___
*[`src/listeners/views/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-NjrqGZjD-j6b-l9BH-d:-NjsQv8c79Z8b8lbQ4dV:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/views/index.ts#L5)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above

**Review by Darth-Raazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52)* status: all files reviewed, 1 unresolved discussion (waiting on @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/commands/index.ts` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-Njrq3ju3PRXyjbGK9n6:-NjsRRgH9L6SnWWEBk3F:bnzy557) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/550b1808b6a92513f375ed06e894d645754cd1f1/src/listeners/commands/index.ts#L5)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Yes, just an example to show how functionality should be added here.
</blockquote></details>

Awesome thanks

**Comment by QuantumManiac** [comment]
I will be getting this task through the finish line as @billyao021031 has been quite busy as of late. PR description updated using template.

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/52#-:-NkC4m1X4HQT94W9pwyU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Pull request merged**
