### PR TITLE
Implement /help command

### LINKED ISSUE #25: Implement `/help` command
Implement a "help" [slash command](https://slack.dev/bolt-js/concepts#commands) that when used, responds to the user who used it with an [ephemeral message](https://api.slack.com/methods/chat.postEphemeral) that directs them to this repo's README (and later to a more formal user guide).

Implementing this command will require its slash command to be added in the Slack App Console (see [here](https://api.slack.com/interactivity/slash-commands) for more info). This will need to be done for the development instance of Minerva now, and the production instance of minerva once it is released

### PR DESCRIPTION
**Pull request by billyao021031**
## Description

I created a helpCommand.ts in the .commands folder and link it to the index.ts for app to listen to the command. The helpCommandHandler function will wait for a '/help' command and then return with an ephemeral message that contains a link to the README.md in our current working repository.
Screenshot 2023-12-10 at 6 58 51 PM

This PR closes #25.

## Developer Testing

Testing done:
- Manually tested the '/help' command in the our development slack bot. 
- Implemented unit tests for the new feature
Screenshot 2023-12-10 at 7 01 49 PM

## Reviewer Testing

Steps to view/test Feature:
1. In the Dev slack, command '/help' in any channel that minerva is in. If minerva is not in a channel, you can add them by pinging them (sending @minervadev in a message)
1. Check if Minvera responds to your command, and make sure the link to README works.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Implemented unit tests for the new feature
I don't see any, have you committed them yet?
If you have yet to write them up, don't worry about it for now. I'm looking into a good way to unit test these kinds of interactions with the Slack API as per #55 

Looks good so far! Left a few comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-:-NlLQ7WL-7-8qeASiWPh:b-h9gfu5)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/commands/helpCommand.ts` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-NlLR2Y1D7WzM4mq3yLq:-NlLR2Y1D7WzM4mq3yLr:b-tln3bl) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/4946262e2c8d895c3ec0218b39059d94d44fc847/src/listeners/commands/helpCommand.ts#L4)):*
> ```XML
> import { Middleware, SlackCommandMiddlewareArgs } from '@slack/bolt';
> 
> const README_URL =
> ```

We probably don't need to have a variable just for the README URL
___
*[`src/listeners/commands/helpCommand.ts` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-NlLQOGd-JjCzNC5kgRZ:-NlLQOGd-JjCzNC5kgR_:bv95q80) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/4946262e2c8d895c3ec0218b39059d94d44fc847/src/listeners/commands/helpCommand.ts#L6)):*
> ```XML
> const README_URL =
>   'https://github.com/waterloo-rocketry/minerva-rewrite/blob/main/README.md';
> const message = `For more information, check out this ${README_URL}!`;
> ```

It might be nice to clean the message up a bit, e.g. by using a link with text. Take a look at the suggestion.



_Suggestion:_
```XML
const message = `For more information, check out <https://github.com/waterloo-rocketry/minerva-rewrite/blob/main/README.md|minerva's README>.`;
```

**Review by billyao021031 — COMMENTED** [review]
I was planning on writing some unit test..Great to see the issue #55

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-:-NlLzQamDlZBd4gVBDkh:bw959lx)* status: all files reviewed, 2 unresolved discussions (waiting on @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/listeners/commands/helpCommand.ts` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-NlLR2Y1D7WzM4mq3yLq:-NlLzH1RDo_-h-8UPxvi:b-vou9vl) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/4946262e2c8d895c3ec0218b39059d94d44fc847/src/listeners/commands/helpCommand.ts#L4)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

We probably don't need to have a variable just for the README URL
</blockquote></details>

I am going to change along with the next comment.
___
*[`src/listeners/commands/helpCommand.ts` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-NlLQOGd-JjCzNC5kgRZ:-NlLzN9J9QBMvdDIjuw_:b-ouq3ir) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/4946262e2c8d895c3ec0218b39059d94d44fc847/src/listeners/commands/helpCommand.ts#L6)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It might be nice to clean the message up a bit, e.g. by using a link with text. Take a look at the suggestion.
</blockquote></details>

Change it in the following commits

**Review by QuantumManiac — APPROVED** [review]
:lgtm:! Please deploy this to developmetn and check if the command works as expected before you squash and merge. I'm not 100% sure if the way the link is formatted is the right way to do so, so it would be good to verify that.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-:-NlO7GCk1eM1BQNn90Pj:b-21oi62)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Comment by billyao021031** [comment]
> :lgtm:! Please deploy this to development and check if the command works as expected before you squash and merge. I'm not 100% sure if the way the link is formatted is the right way to do so, so it would be good to verify that.
> 
> > Reviewed 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/54#-:-NlO7GCk1eM1BQNn90Pj:b-21oi62)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

I tested it out before re-request review, the link was working the way it should be

**Pull request merged**
