### PR TITLE
Implement rollback mechanism and workflow exit during application failure

### PR DESCRIPTION
**Pull request by shirleyfyx**
- Continuous monitoring mechanism for PM2 processes using jq. 
- Adds a conditional installation of jq to ensure that the necessary tools for monitoring are available.
- Create a Backup Folder for Old Development and Rollback Mechanism.
- Closes https://github.com/waterloo-rocketry/minerva-rewrite/issues/40

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51)

### CODE REVIEW

**Comment by shirleyfyx** [comment]
Please don't review the PR yet. The script is working partially. I am still working on fixing the Rollback mechanism. 
image

**Comment by shirleyfyx** [comment]
After communicating with @QuantumManiac, we have decided not to implement the rollback system.

**Comment by shirleyfyx** [comment]
The script passes with successful deployment. As the current application code does not perform any functional operations and consists primarily of an infinite loop for placeholder purposes, this deployment script will only check if PM2 successfully starts the process, regardless of the application's operational state. This is a temporary measure. Once the application is developed further and has meaningful functionality, this script should be updated to reflect more accurate operational checks and monitoring.

image

**Review by Darth-Raazi — APPROVED** [review]
:lgtm: pending small changes

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-:-NjEvhvMDllaMonvaUBp:b-jvz772)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`.github/workflows/deploy_development.yml` line 74 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjEntDd5TTloUABvb_1:-NjEntDd5TTloUABvb_2:bpzo9bd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/f89b477bdbd3e7f94d0d156332c02e679995373d/.github/workflows/deploy_development.yml#L74)):*
> ```YAML
>               echo "PM2 application is not running!"
>               exit 1
>             fi
> ```

Nit: end files with blank lines please
___
*[`src/index.ts` line 3 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjEvapS5N4EEWRg1JW6:-NjEvapS5N4EEWRg1JW7:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/f89b477bdbd3e7f94d0d156332c02e679995373d/src/index.ts#L3)):*
> ```XML
> console.log('There is nothing here yet.');
> console.error('This is an error.');
> while (true) {}
> ```

See above

**Review by Darth-Raazi — APPROVED** [review]
:lgtm: 

Pro tip: You don't have to re-request a review from someone that has already approved, even if they left some small comments. As long as you address them before merging, you're good to go. 

> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-:-NjJ8QRc4k4r0K6XTHBU:b-wm99pm)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @billyao021031, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @QuantumManiac, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Looks good so far, left a few comments.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-:-NjJC6U3CobxSQIrMStb:b-x9aj1)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`.github/workflows/deploy_development.yml` line 18 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJACy96dZdxzLy7w6Q:-NjJACy96dZdxzLy7w6R:b5075bd) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L18)):*
> ```YAML
>         uses: actions/setup-node@v3
>         with:
>           node-version: '18.x'
> ```

I don't think you need to have these quotes here, should be fine as before.
___
*[`.github/workflows/deploy_development.yml` line 45 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAIS93JKokLF88Omz:-NjJAIS93JKokLF88On-:bgfcgao) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L45)):*
> ```YAML
>           username: ${{ secrets.REMOTE_USER }}
>           key: ${{ secrets.REMOTE_KEY }}
>           source: 'dist/'
> ```

See above comment about quotes
___
*[`.github/workflows/deploy_development.yml` line 46 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAKBjC_5PoQ4ZHR2y:-NjJAKBjC_5PoQ4ZHR2z:b9ybpb3) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L46)):*
> ```YAML
>           key: ${{ secrets.REMOTE_KEY }}
>           source: 'dist/'
>           target: '~/minerva-dev-new/'
> ```

See above comments about quotes. Also, since we don't have any rollback mechanism anymore, this should be copying over to `~/minerva-dev/` like before, right?
___
*[`.github/workflows/deploy_development.yml` line 48 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJBk9S2aMoI3eMFqdI:-NjJBk9S2aMoI3eMFqdJ:b4c30vc) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L48)):*
> ```YAML
>           target: '~/minerva-dev-new/'
>           strip_components: 1
>       - name: PM2 process handling
> ```

It think it makes sense to keep the name for this step as the same as before. Maybe if we wanted to be more descriptive, something like "Start pm2 process and monitor startup"?
___
*[`.github/workflows/deploy_development.yml` line 55 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAdQX6Snc9lDc2V-F:-NjJAdQX6Snc9lDc2V-G:b-fgoagl) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L55)):*
> ```YAML
>           key: ${{ secrets.REMOTE_KEY }}
>           script: |
>             # Install jq if it is not already installed
> ```

We don't need an install step for `jq`, we can assume that it's already installed on the server (which it is)
___
*[`.github/workflows/deploy_development.yml` line 60 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAp2Y8rJPiH5bLyUM:-NjJAp2Y8rJPiH5bLyUN:b-9724lu) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L60)):*
> ```YAML
>               sudo apt-get update && sudo apt-get install -y jq
>             fi
>             echo "Changing directory to ~/minerva-dev"
> ```

Probably don't need this to be printed to the log. 
___
*[`.github/workflows/deploy_development.yml` line 64 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAluNEzKGiw7S4e23:-NjJAluNEzKGiw7S4e24:b8f5p7m) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L64)):*
> ```YAML
>       
>             echo "Starting the application with PM2"
>             pm2 start ecosystem.config.js || exit 1
> ```

Any reason for adding the `|| exit 1`?
___
*[`.github/workflows/deploy_development.yml` line 67 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJAvz2BrJ1Wq5efjs4:-NjJAvz30wd74RT6OrRM:b-va0zm4) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L67)):*
> ```YAML
>       
>             # Check if PM2 started the application successfully
>             echo "Checking PM2 process status..."
> ```

We probably need to have a delay of a second or so to let minerva start (and go through its crash loops and fail after the max number of restarts if it's failing) before we check if it's online. My assumption is that minerva would still be in an "online" state while it's in this crash loop, but you might need to confirm that.
___
*[`.github/workflows/deploy_development.yml` line 72 at r5](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjJBXmmEmnLyVJaGzek:-NjJBXmmEmnLyVJaGzel:b-vx9efl) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/3e471ee72d4bd0f67e960bc3e52ddd8ffa6bcca6/.github/workflows/deploy_development.yml#L72)):*
> ```YAML
>               exit 0
>             else
>               echo "PM2 application is not running!"
> ```

Might be better to say "has failed to start" or "has crashed" rather than "is not running".

**Review by shirleyfyx — COMMENTED** [review]
Updated as suggested.

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51)* status: all files reviewed, 2 unresolved discussions (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @shirleyfyx, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

**Review by shirleyfyx — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51)* status: all files reviewed, 1 unresolved discussion (waiting on @billyao021031, @Darth-Raazi, @jeffrey-huang-yz, @Panizghi, @PCModeActivate, @slightlyskepticalpotat, @wxp02, and @yxyyeah)

___
*[`src/index.ts` line 3 at r4](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/51#-NjEvapS5N4EEWRg1JW6:-Njt85jZ2UfHM9pDrh4o:bs7wumb) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/f89b477bdbd3e7f94d0d156332c02e679995373d/src/index.ts#L3)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

**Pull request merged**
