### PR TITLE
Setup CI/CD workflow for unit testing

### PR DESCRIPTION
**Pull request by shirleyfyx**
- Configured GitHub Actions to run unit tests on push.
- Currently, no tests are present in the repository. Modified the testing step to pass even if no tests are found.
- Closes https://github.com/waterloo-rocketry/minerva-rewrite/issues/8

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Looks good so far! Just a few comments.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37#-:-Ngi8Thm2LnaMW3bZ9_M:bju2dnn)* status: all files reviewed, 2 unresolved discussions (waiting on @shirleyfyx)

___
*[`.github/workflows/test.yml` line 30 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37#-Ngi8HFm5cXp8Cs1A48a:-Ngi8HFm5cXp8Cs1A48b:bbyffyc) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/5b533d8f6b847ca411cdbbaa3ac97add5a25d29d/.github/workflows/test.yml#L30)):*
> ```YAML
>       - name: Install dependencies
>         run: yarn install
>         working-directory: ../minerva-rewrite/
> ```

I'm actually not sure why we set the working directory as such because the default working directory should be that anyway. Do you want to try removing these lines and seeing if it actually works?
___
*[`.github/workflows/test.yml` line 33 at r3](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37#-Ngi8PQ68VRB2qH1tNI6:-Ngi8PQ68VRB2qH1tNI7:b-n5gu6p) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/5b533d8f6b847ca411cdbbaa3ac97add5a25d29d/.github/workflows/test.yml#L33)):*
> ```YAML
>       
>       - name: Run unit tests
>         run: yarn test --passWithNoTests
> ```

Have you tried testing this workflow with tests actually existing?

**Comment by shirleyfyx** [comment]
GitHub Actions workflow is correctly set up and running with dummy test cases. 

image

**Comment by shirleyfyx** [comment]
Works without working-directory.

image

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37)* status: all files reviewed, 1 unresolved discussion (waiting on @shirleyfyx)

___
*[`.github/workflows/test.yml` line 8 at r6](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37#-Ngj1MZr1KI-qTO_g1yS:-Ngj1MZr1KI-qTO_g1yT:b-vehiry) ([raw file](https://github.com/waterloo-rocketry/minerva-rewrite/blob/28a25f16ca60cb1adfe7165c2de09e0e19714294/.github/workflows/test.yml#L8)):*
> ```YAML
>         - 'main'
>         - 'development'
>     pull_request:
> ```

I don't think we need `pull_request` because the code being used in the PR will already have been tested due to the `push` condition. If you take a look at this PR, you can see that this workflow was run twice: once for opening the PR and another for pushing the commits in it.

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva-rewrite/37#-:-NglC4B412LO7MRD5Tia:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shirleyfyx)

**Pull request merged**
